### ISSUE TITLE
האפליקציה מציגה חפיפה במקום שלא הייתי בו

### ISSUE THREAD

**Issue by SharonFinkel** [MohGovIL/hamagen-react-native#144] opened 2020-04-01 06:05 UTC
היי, ראיתי שהאפליקציה מציגה שיכול להיות שהייתה חפיפה ביני ובין חולה קורונה במקום ושעה שמאוד רחוקים מהמקום שבו הייתי באותו הזמן. 
האפליקציה הציגה 4 חפיפות כאלה.
האם אתם מכירים באג כזה?

**Comment by Isan-Rivkin** [comment] 2020-04-01 08:00
Same here

**Comment by rafi** [comment] 2020-04-01 11:08
It seems the app is receiving geolocation points retrospectively regarding (only now) confirmed patients and matches your geolocation history movements. In the past 24h I've received around 20 push notifications from the 24th of March chance of exposure. It's good information, however I thought it's a mistake at first impression. After looking on my timeline at that date closely, I realized I __did__ overlap the patient, approx. 200 meters, but I was in a car, driving. Still, "nice to have" data. And seems #145 is going to fix the repetitive push notifications for the same point, gazillion times, even in the middle of the night 🙄

אז לסיכום. יכול להיות שהייתם 100-500 מטרים ליד חולה שרק התברר עכשיו כחולה, אפילו שהייתם ברכב (לא הליכה). כרגע נראה שיש באג באפליקציה שגורם לאותו התרעה להופיע שוב ושוב ונראה ששוחרר כבר תיקון לאייפון לפי #145

**Comment by MoistJohn** [comment] 2020-04-01 14:07
I too am getting repeating notifications for the same two "matches" even after dismissing them.
Unlike @rafi my so called "matches" are for points of data over 2km from my location. I've double checked with my google maps history and during both "matches", I was home all day.

Also, the application does not show an address. It just shows
בדיקת קורונה - חיפה
Which I had to check the health department COVID19 map to find out that it is actually a convention center at the south exit of Haifa.

**Comment by DanielMOH** [comment] 2020-04-01 21:55
We appreciate your ongoing involvement in giving useful feedback on the app. Since the app doesn't transmit any data to the server (to ensure ultimate privacy) we rely on feedback like your comments here to understand where users face issues. It really helps us improve the app!
We fixed most of the bugs that caused the repeated notifications. **Please update to the new version (1.1.2)**, released on 31.3 (note that it might take some time to propagate to all users on the Play/App Stores).

The primary reasons for most repeated notifications and false-alarms were:

- Minor errors with the timestamps of confirmed patients locations (the source of the data is manual epidemiological investigations)
- The fact that the app relied on a relatively lenient radius (500 meters at launch and then 150 meters). We narrowed it down to 50m radius and even consider using building polygons or bounding boxes.
- The fact that the app receives location data from the phone's OS location service in a varying frequency, not controlled directly by the app (because we don't want it to drain the battery).

I'm closing the issue for now. But please, if you still experience repeated notifications or any other bugs - let us know!

**Closed by DanielMOH** 2020-04-01 21:55 UTC
